databases:
  - name: blogdatabse
    databaseName: blogdatabse
    user: carlosrgv

services:
  - type: web
    name: blogpersonal
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogdatabse
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false